// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "autotranslate",
    "name": "Autotranslate",
    "description": "Autotranslate plugin for Mattermost 5.22 and later.",
    "homepage_url": "https://github.com/mattermost/mattermost-plugin-autotranslate",
    "support_url": "https://github.com/mattermost/mattermost-plugin-autotranslate/issues",
    "release_notes_url": "https://github.com/mattermost/mattermost-plugin-autotranslate/releases/tag/v0.4.0",
    "version": "0.4.0",
    "min_server_version": "5.22.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "Provider",
                "display_name": "Translation Provider:",
                "type": "dropdown",
                "help_text": "Select the translation service provider.",
                "placeholder": "",
                "default": "aws",
                "options": [
                    {
                        "display_name": "AWS Translate",
                        "value": "aws"
                    },
                    {
                        "display_name": "vLLM",
                        "value": "vllm"
                    }
                ]
            },
            {
                "key": "AWSAccessKeyID",
                "display_name": "AWS Access Key ID:",
                "type": "text",
                "help_text": "The access key ID from AWS. (Required for AWS provider)",
                "placeholder": "",
                "default": null
            },
            {
                "key": "AWSSecretAccessKey",
                "display_name": "AWS Secret Access Key:",
                "type": "text",
                "help_text": "The secret access key from AWS. (Required for AWS provider)",
                "placeholder": "",
                "default": null
            },
            {
                "key": "AWSRegion",
                "display_name": "AWS Region:",
                "type": "text",
                "help_text": "The region from AWS. (Required for AWS provider)",
                "placeholder": "",
                "default": "us-east-1"
            },
            {
                "key": "VLLMApiURL",
                "display_name": "vLLM API URL:",
                "type": "text",
                "help_text": "The vLLM API endpoint URL (e.g., http://localhost:8000/v1/completions). (Required for vLLM provider)",
                "placeholder": "http://localhost:8000/v1/completions",
                "default": null
            },
            {
                "key": "VLLMApiKey",
                "display_name": "vLLM API Key:",
                "type": "text",
                "help_text": "The API key for vLLM endpoint (optional, leave empty if not required).",
                "placeholder": "Optional",
                "default": null
            },
            {
                "key": "VLLMModel",
                "display_name": "vLLM Model:",
                "type": "text",
                "help_text": "The model name to use for translation (e.g., meta-llama/Llama-2-7b-chat-hf). (Required for vLLM provider)",
                "placeholder": "meta-llama/Llama-2-7b-chat-hf",
                "default": null
            }
        ]
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
